server:
  port: 8101

spring:
  application:
    name: cbr
    
app:
  cache:
    size: 365
  rest:
    api:
      prefix: /api    
    
cbr:
  url: "https://cbr.ru/scripts/XML_daily.asp"
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8100/eureka