spring:
  application:
    name: currencyrateclient

server:
  port: 8080
  
app:
  rest:
    api:
      prefix: /api
      
cbr-rate-client:
  url: "http://CBR/api/v1/currencyRate"
      
moex-rate-client:
  url: "http://MOEX/api/v1/currencyRate"      
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8100/eureka