spring:
  application:
    name: currencyrateclient

server:
  port: 8081
  
app:
  rest:
    api:
      prefix: /api
      
cbr-rate-client:
  url: "http://CBRRATE/api/v1/currencyRate"
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8079/eureka